config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/secret'
  devise_for :users
  
  resources :charges
  resources :users
  resources :events do
  	resources :participations
	end
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
	after_create :inscription_event_email
	validates :user_id, presence: true
	validates :event_id, presence: true


	def inscription_event_email
		UserMailer.inscription_event_email(self).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :user

	validates :start_date, presence: true
	validate :test_start_date
	
	validates :duration, presence: true
	validate :modulo_duration

	validates :title, presence: true, length: { in: 1..140 }

	validates :description, presence: true, length: { in: 20..1000 }

	validates :price, presence: true, numericality: { only_integer: true }, numericality: { greater_than: 1, less_than_or_equal_to: 1000 }

	validates :location, presence: true

	def test_start_date
		if start_date.present? && start_date.to_date < Date.today
			errors.add(:start_date, "can't be in the past")
		end
	end

	def modulo_duration
		if duration.present? && duration % 5 != 0
			errors.add(:duration, "must be a multiple of 5")
    	end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances
	has_many :events, through: :attendances
	after_create :welcome_send

	validates :email, presence: true
	#validates :first_name, presence: true
	#validates :last_name, presence: true

	validates :email, length: { minimum: 3 }
	#validates :first_name, length: { minimum: 3 }
	#validates :last_name, length: { minimum: 3 }
  	def welcome_send
    	UserMailer.welcome_email(self).deliver_now
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]

  def index
    @event = Event.all
  end

  def new
  end

  def edit
    @event = Event.find(params[:id])
  end

    def update
    @event = Event.find(params[:id])
    parasol = params["event"]
    if @event.update(title: parasol["title"], description: parasol["description"], start_date: params["start_date"].to_datetime, duration: parasol["duration"], price: parasol["price"], location: parasol["location"])
      redirect_to "/events/#{params["id"]}"
    else
      render :edit
    end
  end

  def create
	@event = Event.new(title: params["title"], description: params["description"], start_date: params["start_date"], duration: params["duration"], price: params["price"], location: params["location"])
  	@event.user = current_user
    if @event.save
    	redirect_to "/events"
  	else
  		redirect_to "/events/new"
  	end
  end

  def show
    @b = false
    @event = Event.find(params["id"])
    if current_user
    Attendance.all.each do |a|
      if a.user_id == current_user.id
        if a.event_id == @event.id
          @b = true
        end
      end
    end
    end    
  end

  def destroy
    @desevent = Event.find(params["id"])
    if @desevent.attendances.count == 0
      @desevent.destroy
      redirect_to "/events"
    end
    redirect_to "/events"
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
    before_action :authenticate_user!, only: [:create]
  def new
    #if Attendance.where(user: current_user.id.to_s)
    #  redirect_to "/events"
    #end
    @event = Event.find(params["event_id"])
  end

  def create
        # Amount in cents
    @event = Event.find(params["event_id"])

    @amount = @event.price * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    puts "****************************"
    puts params
    @attendance = Attendance.new(user_id: current_user.id, event_id: params["event_id"], stripe_customer_id: params["stripeToken"])
    if @attendance.save
      redirect_to "/events"
    else
      render :new
    end
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end


  def show
    @event = Event.find(params["id"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  def user_id
    if current_user[:id] != (params[:id]).to_i
      	redirect_to "/events"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/charges/create.html.erb
<h1>coucou</h1>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/event/index.html.erb
<div class="d-flex flex-column">
      <div>
        <h1 class="pt-3 pb-3 text-success">accueil de event</h3>
      </div>

	<% @event.each do |event| %>
    	<div class="card mb-4 bg-success text-center">
        	<div class="card-header border border-dark bg-info">
        		<a class="text-warning" href=""><%= event.title %><br/></a>
        	</div>
        	<div class="card-body">
        		<a class="text-warning" href="">author:<%= event.user.email %></a>
                <br/>
                <br/>
        	</div>
    	</div>
   	<% end %>
</div>

app/views/event/new.html.erb
<div class="d-flex flex-column text-center">
	<div>
		<h1 class="pt-3 pb-3 text-success">Create event</h1>
	</div>
	<div>
		<%= form_tag url_for(action: 'create'), method: "post" do %>
			<div class="border border-dark bg-success pt-3 pb-3 text-warning">

			    <%= label_tag 'Title' %>   
			    <%= text_field_tag 'title' %>
			    <br /> <br />

			    <%= label_tag 'decription' %>
			    <%= text_area_tag 'decription' %>
			    <br /> <br />

			    <%= label_tag 'price' %>
			    <%= text_area_tag 'price' %>
			    <br /> <br />

			    <%= label_tag 'location' %>
			    <%= text_area_tag 'location' %>
			    <br /> <br />

			    <%= submit_tag "Create event" %>
		    </div>
		<% end %>
	</div>
</div>

app/views/events/edit.html.erb
<h1>edit <%= @event.title  %></h1>

<%= form_for @event do |f| %>

	<div class="form-group">
		<label>titre de l'event</label>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>description de l'event</label>
		<%= f.text_area :description, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>start_date de l'event</label>
		<%= date_field_tag 'start_date', @start_date, class: "form-control "  %>
	</div>
	<div class="form-group">
		<label>duration de l'event</label>
		<%= f.text_area :duration, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>price de l'event</label>
		<%= f.text_area :price, class: 'form-control' %>
	</div>
	<div class="form-group">
		<label>location de l'event</label>
		<%= f.text_area :location, class: 'form-control' %>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">modifier event</button>
	</div>

<% end %>

app/views/events/index.html.erb
<div class="d-flex flex-column">
      <div>
        <h1 class="pt-3 pb-3 text-success">accueil de event</h3>
          
      </div>
	<% @event.each do |event| %>
    	<div class="card mb-4 bg-success text-center">
        	<div class="card-header border border-dark bg-info">
        		<a class="text-warning" href="/events/<%= event.id %>"><%= event.title %><br/></a>
        	</div>
        	<div class="card-body">
        		<a class="text-warning" href="/events/<%= event.id %>">author:<%= event.user.email %></a>
                <br/>
                <br/>
        	</div>
    	</div>
   	<% end %>
</div>

app/views/events/new.html.erb
<div class="d-flex flex-column text-center">
	<div>
		<h1 class="pt-3 pb-3 text-success">Create event</h1>
	</div>
	<div>
		<%= form_tag url_for(action: 'create'), method: "post" do %>
			<div class="border border-dark bg-success pt-3 pb-3 text-warning">
			    <%= label_tag 'Title' %>   
			    <%= text_field_tag 'title' %>
			    <br /> <br />

			    <%= label_tag 'description' %>
			    <%= text_area_tag 'description' %>
			    <br /> <br />

			    <%= label_tag 'start_date' %>
			    <%= text_area_tag 'start_date' %>
			    <br /> <br />

			    <%= label_tag 'duration' %>
			    <%= text_area_tag 'duration' %>
			    <br /> <br />

			    <%= label_tag 'price' %>
			    <%= text_area_tag 'price' %>
			    <br /> <br />

			    <%= label_tag 'location' %>
			    <%= text_area_tag 'location' %>
			    <br /> <br />

			    <%= submit_tag "Create event" %>
		    </div>
		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<div class="d-flex flex-column">
	<div class="text-center">
		<h1 class="pt-3 pb-3 text-success">voila levent numero : <%= @event.id %></h1>
	</div>
	<div class="text-center bg-success border border-dark">
		<div>
			<h3 class="text-warning border border-dark bg-info pt-2 pb-2">titre : <%= @event.title %></h2>
		</div>
		<p class="text-warning"><%= @event.title %></p>
		<p class="text-warning">crée le : <%= @event.description %></p>
		<br/>
		<a class="text-info pr-5" href="/users/<%= @event.user.id %>">author : <%= @event.user.email %></a>
		<p class="text-warning">start date : <%= @event.start_date %></p>
		<p class="text-warning">duration : <%= @event.duration %></p>
		<p class="text-warning">price : <%= @event.price %></p>
		<p class="text-warning">location : <%= @event.location %></p>
		<% if current_user == @event.user %>
			<a class="text-info pr-5" href="/events/<%= @event.id %>/participations/<%= @event.id %>">nombre de participation : <%= @event.attendances.count %></a>
		<% elsif current_user != @event.user && @b != true && current_user%>
			<p class="text-warning">nombre de participation : <%= @event.attendances.count %></p>
			<a class="text-info pr-5" href="/events/<%= @event.id %>/participations/new">participe??</a>
		<% else %>
			<p class="text-warning">nombre de participation : <%= @event.attendances.count %></p>
		<% end %>
	</div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<div>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email : <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Secret page", home_secret_path %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>
</div>

app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoblinWorld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <% @user = current_user %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

          <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    
  </head>

  <body class="bg-warning text-center">
    <nav class="pt-4 pb-2 d-flex justify-content-between bg-success">
      <a class="pr-5 text-warning" href="/events">accueil</a>

      <div>
        <% if current_user %>
        <a class="pr-3 text-warning" href="/users/<%= @user.id %>">profile</a>
        <a class="pr-5 text-danger h4" href="/users/sign_out" data-method="delete">deconect</a>
        <% else %>
        <a class="text-info h4" href="/users/sign_in">login</a>
        <a class="pr-3 text-warning" href="/users/sign_up">inscrire</a>
        <% end %>
        <a class="pr-3 text-warning" href="/events/new">create event</a>


      </div>
    </nav>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/participations/new.html.erb
<%= form_tag event_participations_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @event.price * 100 %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<% @event.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/participations/show.html.erb
<h1><%= @event.title %></h1>
<p class="">inscrit : <%= @event.attendances.count %></p>
<a class="text-info h4" href="/events/<%= @event.id %>/edit">edit</a>
<a class="font-weight-light text-danger" href="<%=event_path(@event.id)%> "data-confirm= 'Are you sure ?' data-method="DELETE">Delete event</a>


<div>
	<% @event.attendances.each do |event| %>
    	<div class="card mb-4 bg-success text-center">
        	<div class="card-header border border-dark bg-info">
        		<p class="text-warning">participe :<%= event.user.email %></p>
        	</div>
        	<div class="card-body">
        		<p class="text-warning">description :<%= event.user.description %></p>
                <br/>
                <br/>
        	</div>
    	</div>
   	<% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="d-flex flex-column">
	<div class="text-center">
		<h1 class="pt-3 pb-3 text-success">voila le gossip numero : <%= @user.id %></h1>
	</div>
	<div class="text-center bg-success border border-dark">
		<div>
			<h3 class="text-warning border border-dark bg-info pt-2 pb-2">pseudo : <%= @user.first_name %></h2>
		</div>
		<p class="text-warning"><%= @user.email %></p>
		<p class="text-warning">crée le : <%= @user.created_at %></p>
		<br/>
		<% if current_user %>
			<a href="" class="btn btn-danger " data-confirm="sur?" data-method="delete">delete</a>
		<% else %>
			<a href="/sessions/new" class="btn btn-danger " data-confirm="sur?" data-method="delete">delete</a>
		<% end %>
	</div>
</div>